export const AUTH_START   = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_LOGIN_FAIL    = 'AUTH_LOGIN_FAIL'
export const AUTH_LOGOUT  = 'AUTH_LOGOUT'

export const LOGGED_IN_USER_INFO = 'LOGGED_IN_USER_INFO'
export const NEW_ORDER_COUNT = 'NEW_ORDER_COUNT'

export const MARCHENT_ORDER_LIST = 'MARCHENT_ORDER_LISR'
export const ADMIN_ORDER_LISR = 'ADMIN_ORDER_LISR'
export const LIST_OF_MERCHANT = 'LIST_OF_MERCHANT'


export const REMOVE_SUCCESS_PLACED = 'REMOVE_SUCCESS_PLACED'
export const PLACE_ORDER_SUCCESS = 'PLACE_ORDER_SUCCESS'
export const PLACE_ORDER_FAIL = 'PLACE_ORDER_FAIL'