# Generated by Django 3.2 on 2021-04-24 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceNewOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percel_name', models.CharField(max_length=250)),
                ('percel_type', models.CharField(choices=[('Fragile', 'Fragile'), ('Liquid', 'Liquid')], default='Fragile', max_length=100)),
                ('newInvoiceID', models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True)),
                ('weight', models.CharField(max_length=10)),
                ('cost', models.CharField(blank=True, max_length=6, null=True)),
                ('cod_charge', models.CharField(blank=True, max_length=6, null=True)),
                ('return_charge', models.CharField(blank=True, max_length=6, null=True)),
                ('total_cost', models.CharField(max_length=6)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('marchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addMarchent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Marchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marchant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
