# Generated by Django 3.2 on 2021-04-24 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('placeNewOrder', '0009_placeneworder_weight_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marchant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marchant', to=settings.AUTH_USER_MODEL),
        ),
    ]
